In [107]:
# Day 1

import numpy as np

In [108]:
# Create numpy array using python list

x = np.array([1,2,3])
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: {}".format(x) )

Dimension: (3,)
data Type: int32
type: <class 'numpy.ndarray'>
Values: [1 2 3]


In [109]:
# numpy array hold string

x = np.array(["hello","World"])
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: {}".format(x) )

Dimension: (2,)
data Type: <U5
type: <class 'numpy.ndarray'>
Values: ['hello' 'World']


In [110]:
# numpy can't hold different datatype it'll interpt all elements as string

x = np.array([1,2,"World"])
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: {}".format(x) )

Dimension: (3,)
data Type: <U11
type: <class 'numpy.ndarray'>
Values: ['1' '2' 'World']


In [111]:
# numpy can't hold different datatype it'll interpt all elements as float (Upcasting)

x = np.array([1,2.0,3,4])
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: {}".format(x) )

Dimension: (4,)
data Type: float64
type: <class 'numpy.ndarray'>
Values: [1. 2. 3. 4.]


In [112]:
# we can set dtype druing initilization of ndarray by using keyword dtype

x = np.array([1,2,3,4],dtype=np.float64)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: {}".format(x) )

Dimension: (4,)
data Type: float64
type: <class 'numpy.ndarray'>
Values: [1. 2. 3. 4.]


In [113]:
# multi dimension array in numpy

x = np.array([[1,2],[1,2],[1,2]])
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (3, 2)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[[1 2]
 [1 2]
 [1 2]]


In [114]:
# we can save numpy array for future use un different program as well
# it's save in .npy extension file

x = np.array(["This","data","is","saved"])
np.save('my_array',x)

In [115]:
# Load array from 'my_array.npy' file
# note we must put .npy on the last of the file name

y = np.load('my_array.npy')
print( "Dimension: {}".format(y.shape) )
print( "data Type: {}".format(y.dtype) )
print( "type: {}".format(type(y)) )
print( "Values: \n{}".format(y) )

Dimension: (4,)
data Type: <U5
type: <class 'numpy.ndarray'>
Values: 
['This' 'data' 'is' 'saved']


In [116]:
# numpy array using built-in function
# Creating ndarray full of zeros

x = np.zeros((3,3))
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (3, 3)
data Type: float64
type: <class 'numpy.ndarray'>
Values: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [118]:
# ndarray full of ones 

x = np.ones((3,4),dtype=np.int64)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (3, 4)
data Type: int64
type: <class 'numpy.ndarray'>
Values: 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [119]:
# ndarray full of any number you want 

x = np.full((3,4),5)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (3, 4)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [120]:
# creating identity matrix

x = np.eye(3,dtype=np.int64)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (3, 3)
data Type: int64
type: <class 'numpy.ndarray'>
Values: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [121]:
# diagnal value with our own choice

x = np.diag([1,2,3,4])
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (4, 4)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [122]:
# evenly space values with a given interval

x = np.arange(3)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

print()
 
x = np.arange(3,10)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

print()
 
x = np.arange(3,10,2)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (3,)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[0 1 2]

Dimension: (7,)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[3 4 5 6 7 8 9]

Dimension: (4,)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[3 5 7 9]


In [123]:
# np.linspace function for interval between fixed values start and stop
# Default generate 50 values between given values [start and Stop]

x = np.linspace(0,10)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (50,)
data Type: float64
type: <class 'numpy.ndarray'>
Values: 
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [125]:
# we can set how many value we want between interval [start,stop]

x = np.linspace(0,10,6)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (6,)
data Type: float64
type: <class 'numpy.ndarray'>
Values: 
[ 0.  2.  4.  6.  8. 10.]


In [126]:
# we can set that stop value will be exclusive by suing keyword endpoint=False

x = np.linspace(0,10,5,endpoint=False)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (5,)
data Type: float64
type: <class 'numpy.ndarray'>
Values: 
[0. 2. 4. 6. 8.]


In [127]:
# we can create 1darray into ndarray by using np.reshape

x = np.arange(0,10)
x = np.reshape(x,(2,5))
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (2, 5)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [128]:
# we can do this in a signle line by this

x = np.arange(0,10).reshape(2,5)
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (2, 5)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [129]:
# generate random number using numpy values between [0.0,1.0)

x = np.random.random((2,2))
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (2, 2)
data Type: float64
type: <class 'numpy.ndarray'>
Values: 
[[0.31211994 0.13142271]
 [0.88517215 0.14934555]]


In [130]:
# generate random number using numpy values between user wants any number [start,stop)

x = np.random.randint(1,3,(4,4))
print( "Dimension: {}".format(x.shape) )
print( "data Type: {}".format(x.dtype) )
print( "type: {}".format(type(x)) )
print( "Values: \n{}".format(x) )

Dimension: (4, 4)
data Type: int32
type: <class 'numpy.ndarray'>
Values: 
[[2 2 2 1]
 [1 1 1 1]
 [1 1 2 1]
 [1 2 2 2]]


In [131]:
# generate random number that satisfy the certain statistical properties

x = np.random.normal(0,0.1,size=(100,100))
print( "mean: {}".format( x.mean()) )
print( "max: {}".format( x.max()) )
print( "min: {}".format( x.min()) )
print( "(x<0): {}".format( (x<0).sum()) )
print( "(x>0): {}".format( (x>0).sum()) )

mean: 0.0011214924521027673
max: 0.43441978028833134
min: -0.41821611047460583
(x<0): 4940
(x>0): 5060
