In [132]:
# Day 2

In [133]:
import numpy as np

In [136]:
# access Elements from indicies

x = np.array([1,2,3])
print("Positve indicies")
print("0 :{}".format(x[0]))
print("1 :{}".format(x[1]))
print("2 :{}".format(x[2]))
print()
print("Negative indicies")
print("-3 :{}".format(x[-3]))
print("-2 :{}".format(x[-2]))
print("-1 :{}".format(x[-1]))

Positve indicies
0 :1
1 :2
2 :3

Negative indicies
-3 :1
-2 :2
-1 :3


In [140]:
# Change Value of ndarray using index

x = np.array([1,2,3])
x[0] = 10

print("x: {}".format(x))

x: [10  2  3]


In [192]:
# Access and Modify Elements from 2darray

x = np.arange(6).reshape(2,3)
print("initial array")
print("x :\n{}".format(x))

print()

print("access Element from array")
print("[0, 1] :{}".format(x[0, 1]))


x[1, 2] = 100  # modify signle elements
x[0,:] = 200 # modify Complete Row
x[:,0] = 300 # modify Complete column

print()

print("Modified array")
print("x :\n{}".format(x))

initial array
x :
[[0 1 2]
 [3 4 5]]

access Element from array
[0, 1] :1

Modified array
x :
[[300 200 200]
 [300   4 100]]


In [157]:
# delete Elements from the 1darray

x = np.array([1,2,3,4])
print("initial array")
print("x :{}".format(x))
x = np.delete(x,[0]) # delete First Value
x = np.delete(x,[0,2]) # delete second and fourth Value
print()
print("Modified array")
print("x :{}".format(x))

initial array
x :[1 2 3 4]

Modified array
x :[3]


In [171]:
# delete Elements from the 1darray
# axis = 0 is row and axis = 1 is column

x = np.arange(15).reshape(3,5)
print("initial array")
print("x:\n{}".format(x))

print()

x = np.delete(x,1,axis=0)
print("Second Row deleted")
print("x:\n{}".format(x))

print()

x = np.delete(x,[0,(x.shape[1]-1)],axis=1)
print("1st and last column deleted")
print("x:\n{}".format(x))

initial array
x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Second Row deleted
x:
[[ 0  1  2  3  4]
 [10 11 12 13 14]]

1st and last column deleted
x:
[[ 1  2  3]
 [11 12 13]]


In [173]:
# we can Append Value in ndarray which will insert into the last of the array

x = np.arange(6)
print("initial array")
print("x:\n{}".format(x))

print()

x = np.append(x,6)
print("append 6")
print("x:\n{}".format(x))

print()

x = np.append(x,[7,8])
print("append [7,8]")
print("x:\n{}".format(x))

initial array
x:
[0 1 2 3 4 5]

append 6
x:
[0 1 2 3 4 5 6]

append [7,8]
x:
[0 1 2 3 4 5 6 7 8]


In [178]:
# append value in 2darray

x = np.arange(8).reshape(2,4)

print("initial array")
print("x:\n{}".format(x))

print()

x = np.append(x,[[10,20,40,50]],axis=0)
print("add row into the array")
print("x:\n{}".format(x))

print()

x = np.append(x,[[100],[200],[400]],axis=1)
print("add column into the array")
print("x:\n{}".format(x))

initial array
x:
[[0 1 2 3]
 [4 5 6 7]]

add row into the array
x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [10 20 40 50]]

add column into the array
x:
[[  0   1   2   3 100]
 [  4   5   6   7 200]
 [ 10  20  40  50 400]]


In [195]:
# we can insert a value in 1darray

x = np.array([1,2,3])

print("initial array")
print("x:\n{}".format(x))

print()

x = np.insert(x,1,[20,30])

print("inserted 20 and 30 into position 1")
print("x:\n{}".format(x))

print()

initial array
x:
[1 2 3]

inserted 20 and 30 into position 1
x:
[ 1 20 30  2  3]



In [207]:
# we can insert a value in ndarray

x = np.arange(10).reshape(2,5)
y = np.arange(10,15)
z = np.arange(15,18)

print("initial array")
print("x:\n{}".format(x))

print()

x = np.insert(x,1,y,axis=0)
print("inserted y between 1 and 3 rows")
print("x:\n{}".format(x))

print()

x = np.insert(x,1,z,axis=1)
print("inserted z between 1 and 3 rows")
print("x:\n{}".format(x))

print()

x = np.insert(x,0,1,axis=1)
print("inserted 1s from the start column")
print("x:\n{}".format(x))

initial array
x:
[[0 1 2 3 4]
 [5 6 7 8 9]]

inserted y between 1 and 3 rows
x:
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]]

inserted z between 1 and 3 rows
x:
[[ 0 15  1  2  3  4]
 [10 16 11 12 13 14]
 [ 5 17  6  7  8  9]]

inserted 1s from the start column
x:
[[ 1  0 15  1  2  3  4]
 [ 1 10 16 11 12 13 14]
 [ 1  5 17  6  7  8  9]]


In [223]:
# hstack and vstack

x = np.arange(10).reshape(2,5)
y = np.arange(50,55)
z = np.arange(60,63).reshape(3,1)

print("initial array")
print("x:\n{}".format(x))

print()

x = np.vstack((y,x))
print("y top and x will be bottom")
print("x:\n{}".format(x))

print()

x = np.hstack((z,x))
print("z left and x will be right")
print("x:\n{}".format(x))

initial array
x:
[[0 1 2 3 4]
 [5 6 7 8 9]]

y top and x will be bottom
x:
[[50 51 52 53 54]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]]

z left and x will be right
x:
[[60 50 51 52 53 54]
 [61  0  1  2  3  4]
 [62  5  6  7  8  9]]
