In [1]:
# Day 2 Slicing

In [2]:
import numpy as np

In [15]:
# extract Elements Through slicing

print("Initial arrya")
x = np.arange(20).reshape(4,5)
print("x:\n{}".format(x))

print()

print("extract row from 1 to 3 and column 2 to 4")
z = x[1:4,2:5]
print("z:\n{}".format(z))

print()

print("Extract same as above but differnet Method")
w = x[1:,2:5]
print("w:\n{}".format(w))

print()

print("Extract row till 2nd and column from 2 to 4")
y = x[:3,2:5]
print("y:\n{}".format(y))

print()

print("Extract 2 row")
v = x[2,:]
print("v:\n{}".format(v))

Initial arrya
x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

extract row from 1 to 3 and column 2 to 4
z:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Extract same as above but differnet Method
w:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Extract row till 2nd and column from 2 to 4
y:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

Extract 2 row
v:
[10 11 12 13 14]


In [16]:
print("Extract 2nd column as a 2d array")
R = x[:,2:3]
print("R:\n{}".format(R))

print()

print("Extract 2nd column as a 1d array")
R = x[:,2]
print("R:\n{}".format(R))

Extract 2nd column as a 2d array
R:
[[ 2]
 [ 7]
 [12]
 [17]]

Extract 2nd column as a 1d array
R:
[ 2  7 12 17]


In [34]:
# when we assign slicing into another variable it's just mirring
# if we change one variable from mirror variable it's also effect original variable

x = np.arange(10).reshape(2,5)

print("Initial arrya")
print("x:\n{}".format(x))

print()

z = x[1,:]
z[0] = 100

# it's affect original variable
print("x:\n{}".format(x))

Initial arrya
x:
[[0 1 2 3 4]
 [5 6 7 8 9]]

x:
[[  0   1   2   3   4]
 [100   6   7   8   9]]


In [35]:
# numpy provide us to np.copy method to copy one array into another

x = np.arange(10).reshape(2,5)

print("Initial arrya")
print("x:\n{}".format(x))

print()

z = x[1,:].copy() # or np.copy(x[1,:])
z[0] = 100

# it doesn't affect original variable
print("x:\n{}".format(x))

Initial arrya
x:
[[0 1 2 3 4]
 [5 6 7 8 9]]

x:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [36]:
# we can use 1darray as indcies to extract ndarray elements

x = np.arange(20).reshape(4,5)
ind = np.array([1,2,3])

print("Initial arrya")
print("x:\n{}".format(x))

print()

print("Extract 1 to 3 column using ind variable")
z = x[:,ind]
print(z)

Initial arrya
x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Extract 1 to 3 column using ind variable
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [44]:
# we can use numpy builtin function to select specific elemets in matrix

x = np.arange(25).reshape(5,5)

print("Initial arrya")
print("x:\n{}".format(x))

print()

print("Extract Diognal elements")
z = np.diag(x)
print("x:\n{}".format(z))

print("Extract upper value of Diognal elements using keyword k")
z = np.diag(x, k=1)
print("x:\n{}".format(z))

print("Extract bottom value of Diognal elements using keyword k")
z = np.diag(x, k=-1)
print("x:\n{}".format(z))

Initial arrya
x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Extract Diognal elements
x:
[ 0  6 12 18 24]
Extract upper value of Diognal elements using keyword k
x:
[ 1  7 13 19]
Extract bottom value of Diognal elements using keyword k
x:
[ 5 11 17 23]


In [47]:
# we can Extract unique value from the ndarray

x = np.array([[1,2],[1,2],[2,3],[4,5]])

print("Initial arrya")
print("x:\n{}".format(x))

print()

print("Extract Unique value from array")
z = np.unique(x)
print(z)

Initial arrya
x:
[[1 2]
 [1 2]
 [2 3]
 [4 5]]

Extract Unique value from array
[1 2 3 4 5]
