In [1]:
# Day 3.3

# Mini Project

# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [2]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5000,size=(1000,20))

# print the shape of X
print(X)

[[2159 1138 2452 ... 4618 2761  742]
 [1268 2864 2251 ... 2381  291  103]
 [4920 4525  439 ... 4766 1338 3990]
 ...
 [4665 2464 1020 ... 3515 1165  852]
 [4565 3630 2135 ...  412 1501 4500]
 [ 159 3096  493 ... 4070 2458 2937]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [3]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [5]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [7]:
# Mean normalize X
X_norm = (X-ave_cols)/std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [10]:
X_mean = X_norm.mean()
# Print the average of all the values of X_norm
print(X_mean)

# Print the average of the minimum value in each column of X_norm
print(X_norm.mean(axis=0))

# Print the average of the maximum value in each column of X_norm
print(X_norm.mean(axis=1))

1.0302869668521452e-17
[ 1.02140518e-17 -2.48134846e-17  8.17124146e-17  4.97379915e-17
 -9.40914013e-17  5.01820807e-17  1.22041266e-16 -2.39808173e-17
 -1.68753900e-17 -7.10542736e-18 -9.85878046e-17 -4.19664303e-17
 -9.68114477e-17  3.35287353e-17 -2.06501483e-17  1.31228362e-16
  6.57252031e-17 -4.06341627e-17  2.05460648e-17 -2.29816166e-17]
[ 8.46597243e-02 -1.93879787e-01  1.44596428e-01  3.17087372e-01
 -4.01366625e-02 -2.02953840e-01  5.48091204e-01  2.10202103e-01
 -2.38638076e-01  1.56357351e-02  1.14784023e-01 -5.15869837e-01
 -1.36714498e-01  1.54763130e-01  5.60683011e-01  4.90618331e-02
 -3.06849897e-01  2.16380316e-01 -6.68440162e-02 -3.03086814e-01
  2.08314531e-01 -7.29546582e-02 -2.07265384e-01  7.37959668e-02
 -1.64737254e-01 -2.85887260e-02  3.39558388e-01 -3.38568417e-01
  1.06042398e-01  7.33080056e-03  2.85637962e-01  2.43083787e-01
  1.79037584e-01  1.58956811e-01  1.01276781e-01  3.13548925e-01
  1.46416428e-01 -2.05271188e-01 -3.96875932e-01  2.65425678e-01
 

You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [25]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([2, 1, 0, 3, 4])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [28]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [94]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[:int(len(X_norm)*0.6)]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[int(len(X_norm)*0.6):int(len(X_norm)*0.8)]]

# Create a Test Set
X_test = X_norm[row_indices[int(len(X_norm)*0.8):]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [102]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(600, 20)
(200, 20)
(200, 20)
