In [1]:
# Day 4

In [2]:
import numpy as np

In [16]:
# find Throught Boolean Indexing 1darray

x = np.arange(10)
print("Original array:\n{}".format(x))

print()

print("value less than 7:\n{}".format(x[x<7]))

print()

print("values less than 7 and greather than 2:\n{}".format((x[(x<7) & (x>2)])))

print()

# assign Value to those elements which are satisfy boolean equation
x[x < 7] = -1
print("Modified array:\n{}".format(x))

Original array:
[0 1 2 3 4 5 6 7 8 9]

value less than 7:
[0 1 2 3 4 5 6]

values less than 7 and greather than 2:
[3 4 5 6]

Modified array:
[-1 -1 -1 -1 -1 -1 -1  7  8  9]


In [54]:
# find Throught Boolean Indexing 2darray

x = np.arange(10).reshape(2,5)
print("Original array:\n{}".format(x))

print()

print("value less than 7 in first Row:\n{}".format(x[0][x[0]<7]))

print()

print("value less than 7 in Second Row:\n{}".format(x[1][x[1]<7]))

print()

y =  x[:,2].copy()
print("value less than 7 in 3rd column:\n{}".format(y[y<7]))

print()

print("values less than 7 and greather than 2:\n{}".format((x[(x<7) & (x>2)])))

print()

# assign Value to those elements which are satisfy boolean equation
x[x < 7] = -1
print("Modified array:\n{}".format(x))

Original array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

value less than 7 in first Row:
[0 1 2 3 4]

value less than 7 in Second Row:
[5 6]

value less than 7 in 3rd column:
[2]

values less than 7 and greather than 2:
[3 4 5 6]

Modified array:
[[-1 -1 -1 -1 -1]
 [-1 -1  7  8  9]]


In [58]:
# we can do set operation in 1darray

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,2,4])

print("Intersection:\n{}".format(np.intersect1d(x,y)))
print()
print("Differece :\n{}".format(np.setdiff1d(x,y)))
print()
print("Union:\n{}".format(np.union1d(x,y)))

Intersection:
[2 4]
Differece :
[1 3 5]
Union:
[1 2 3 4 5 6 7 8]


In [65]:
# we can do set operation in ndarray

x = np.array([[1,2,3,4,5],[1,2,3,4,5]])
y = np.array([[6,9,8,2,8],[1,2,3,4,4]])

print("Intersection:\n{}".format(np.intersect1d(x,y)))
print()
print("Differece :\n{}".format(np.setdiff1d(x,y)))
print()
print("Union:\n{}".format(np.union1d(x,y)))

Intersection:
[1 2 3 4]

Differece :
[5]

Union:
[1 2 3 4 5 6 8 9]


In [71]:
# we can sort 1darray thorught two method np.sort(array) Or array.sort()

x = np.random.randint(10,20,size=(10,))

print("Original array:\n{}".format(x))

print()

print("sorted array:\n{}".format(np.sort(x)))

print()

print("but not save in memory:\n{}".format(x))

print()

x.sort()
print("this will save in memory:\n{}".format(x))

print()

Original array:
[15 16 11 17 10 15 12 11 11 11]

sorted array:
[10 11 11 11 11 12 15 15 16 17]

but not save in memory:
[15 16 11 17 10 15 12 11 11 11]

this will save in memory:
[10 11 11 11 11 12 15 15 16 17]



In [76]:
# we can sort ndarray thorught two method np.sort(array) Or array.sort()

x = np.random.randint(0,50,size=(10,10))

print("Original array:\n{}".format(x))

print()

print("sorted array as a column:\n{}".format(np.sort(x,axis=0)))

print()

print("but not save in memory:\n{}".format(x))

print()

x.sort(axis=1)
print("this will save in memory and sort as a row:\n{}".format(x))

print()

Original array:
[[14 22 39 16 39 49 28 13  7 13]
 [10 23 37  3 12 14 21  1 12 38]
 [41 13 48 17 33 27 12 41 20 13]
 [11 11  8 35 38  4 26 40 13  1]
 [48 18 28 37 13 19 40 36 27 14]
 [23 18  5  7 47 16 28 49 23 35]
 [46 19 21  7 26 22 43 24 27 18]
 [46 31 21 49 36 13 20  0  3 35]
 [29 15 46 41 12 21 21 34 27 25]
 [ 6 26 44 33 47 17 28 42 43 29]]

sorted array as a column:
[[ 6 11  5  3 12  4 12  0  3  1]
 [10 13  8  7 12 13 20  1  7 13]
 [11 15 21  7 13 14 21 13 12 13]
 [14 18 21 16 26 16 21 24 13 14]
 [23 18 28 17 33 17 26 34 20 18]
 [29 19 37 33 36 19 28 36 23 25]
 [41 22 39 35 38 21 28 40 27 29]
 [46 23 44 37 39 22 28 41 27 35]
 [46 26 46 41 47 27 40 42 27 35]
 [48 31 48 49 47 49 43 49 43 38]]

but not save in memory:
[[14 22 39 16 39 49 28 13  7 13]
 [10 23 37  3 12 14 21  1 12 38]
 [41 13 48 17 33 27 12 41 20 13]
 [11 11  8 35 38  4 26 40 13  1]
 [48 18 28 37 13 19 40 36 27 14]
 [23 18  5  7 47 16 28 49 23 35]
 [46 19 21  7 26 22 43 24 27 18]
 [46 31 21 49 36 13 20  0  3 35]
 [29 1