In [1]:
# Day 3.2

In [2]:
import numpy as np

In [10]:
# We can do basic mathematical oprtion using numpy of 1darray

x = np.arange(10)
y = np.arange(10,20)

print("x + y: \n{}".format(x+y))
print()
print("np.add(x,y): \n{}".format(np.add(x,y)))
print()
print("x - y: \n{}".format(x-y))
print()
print("np.subtract(x,y): \n{}".format(np.subtract(x,y)))
print()
print("x * y: \n{}".format(x*y))
print()
print("np.multiply(x,y): \n{}".format(np.multiply(x,y)))
print()
print("x / y: \n{}".format(x/y))
print()
print("np.divide(x,y): \n{}".format(np.divide(x,y)))
print()

x + y: 
[10 12 14 16 18 20 22 24 26 28]

np.add(x,y): 
[10 12 14 16 18 20 22 24 26 28]

x - y: 
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]

np.subtract(x,y): 
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]

x * y: 
[  0  11  24  39  56  75  96 119 144 171]

np.multiply(x,y): 
[  0  11  24  39  56  75  96 119 144 171]

x / y: 
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]

np.divide(x,y): 
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]



In [11]:
# We can do basic mathematical oprtion using numpy of ndarray

x = np.arange(10).reshape(2,5)
y = np.arange(10,20).reshape(2,5)

print("x + y: \n{}".format(x+y))
print()
print("np.add(x,y): \n{}".format(np.add(x,y)))
print()
print("x - y: \n{}".format(x-y))
print()
print("np.subtract(x,y): \n{}".format(np.subtract(x,y)))
print()
print("x * y: \n{}".format(x*y))
print()
print("np.multiply(x,y): \n{}".format(np.multiply(x,y)))
print()
print("x / y: \n{}".format(x/y))
print()
print("np.divide(x,y): \n{}".format(np.divide(x,y)))
print()

x + y: 
[[10 12 14 16 18]
 [20 22 24 26 28]]

np.add(x,y): 
[[10 12 14 16 18]
 [20 22 24 26 28]]

x - y: 
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]

np.subtract(x,y): 
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]

x * y: 
[[  0  11  24  39  56]
 [ 75  96 119 144 171]]

np.multiply(x,y): 
[[  0  11  24  39  56]
 [ 75  96 119 144 171]]

x / y: 
[[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444 0.47368421]]

np.divide(x,y): 
[[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444 0.47368421]]



In [16]:
# Mathematical Function provided by numpy

x = np.array([[1,2],[3,4]])

print("exp: \n{}".format(np.exp(x)))
print()
print("sqrt: \n{}".format(np.sqrt(x)))
print()
print("square: \n{}".format(np.power(x,2)))

exp: 
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

sqrt: 
[[1.         1.41421356]
 [1.73205081 2.        ]]

square: 
[[ 1  4]
 [ 9 16]]


In [27]:
# statisticall Function provided by numpy

# Mean
x = np.array([[1,2],[3,4]])

print("x: \n{}".format(x))
print()
print("Mean of array: \n{}".format(x.mean()))
print()
print("Mean of columns: \n{}".format(x.mean(axis=0)))
print()
print("Mean of rows: \n{}".format(x.mean(axis=1)))
print()

x: 
[[1 2]
 [3 4]]

Mean of array: 
2.5

Mean of columns: 
[2. 3.]

Mean of rows: 
[1.5 3.5]



In [28]:
# statisticall Function provided by numpy

# sum
x = np.array([[1,2],[3,4]])

print("x: \n{}".format(x))
print()
print("sum of array: \n{}".format(x.sum()))
print()
print("sum of columns: \n{}".format(x.sum(axis=0)))
print()
print("sum of rows: \n{}".format(x.sum(axis=1)))
print()

x: 
[[1 2]
 [3 4]]

sum of array: 
10

sum of columns: 
[4 6]

sum of rows: 
[3 7]



In [29]:
# statisticall Function provided by numpy

# std
x = np.array([[1,2],[3,4]])

print("x: \n{}".format(x))
print()
print("std of array: \n{}".format(x.std()))
print()
print("std of columns: \n{}".format(x.std(axis=0)))
print()
print("std of rows: \n{}".format(x.std(axis=1)))
print()

x: 
[[1 2]
 [3 4]]

std of array: 
1.118033988749895

std of columns: 
[1. 1.]

std of rows: 
[0.5 0.5]



In [31]:
# statisticall Function provided by numpy

# median must use np.median()
x = np.array([[1,2],[3,4]])

print("x: \n{}".format(x))
print()
print("median of array: \n{}".format(np.median(x)))
print()
print("median of columns: \n{}".format(np.median(x,axis=0)))
print()
print("median of rows: \n{}".format(np.median(x,axis=1)))
print()

x: 
[[1 2]
 [3 4]]

median of array: 
2.5

median of columns: 
[2. 3.]

median of rows: 
[1.5 3.5]



In [35]:
# statisticall Function provided by numpy

# max 
x = np.array([[1,2],[3,4]])

print("x: \n{}".format(x))
print()
print("max of array: \n{}".format(x.max()))
print()
print("max of columns: \n{}".format(x.max(axis=0)))
print()
print("max of rows: \n{}".format(x.max(axis=1)))
print()

#min
print("min of array: \n{}".format(x.min()))
print()
print("min of columns: \n{}".format(x.min(axis=0)))
print()
print("min of rows: \n{}".format(x.min(axis=1)))
print()

x: 
[[1 2]
 [3 4]]

max of array: 
4

max of columns: 
[3 4]

max of rows: 
[2 4]

min of array: 
1

min of columns: 
[1 2]

min of rows: 
[1 3]



In [37]:
# BroadCast Scaler to Matrix

x = np.array([[1,2],[3,4]])

print("x: \n{}".format(x))
print()
print("3 + x: \n{}".format(np.add(3,x)))
print()
print("3 - x: \n{}".format(np.subtract(3,x)))
print()
print("3 * x: \n{}".format(3*x))
print()
print("3 / x: \n{}".format(3/x))
print()

x: 
[[1 2]
 [3 4]]

3 + x: 
[[4 5]
 [6 7]]

3 - x: 
[[ 2  1]
 [ 0 -1]]

3 * x: 
[[ 3  6]
 [ 9 12]]

3 / x: 
[[3.   1.5 ]
 [1.   0.75]]



In [46]:
# BroadCast Matrix to Matrix

x = np.array([1,2,3])

y = np.arange(9).reshape(3,3)


print("x:\n{}".format(x))
print()
print("y:\n{}".format(y))
print()
print("x add into y each row:\n{}".format(x+y))
print()
print("x add into y each columns:\n{}".format(x.reshape(-1,1) + y))
print()

x:
[1 2 3]

y:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

x add into y each row:
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]

x add into y each row:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]



In [48]:
# Becarfull when this thing happen

x = np.array([1,2,3])

print("x(1*3):\n{}".format(x))
print()
print("x(3*1):\n{}".format(x.reshape(-1,1)))
print()
print("x(1*3) + x(3*1):\n{}".format(x+x.reshape(-1,1)))

x(1*3):
[1 2 3]

x(3*1):
[[1]
 [2]
 [3]]

x(1*3) + x(3*1):
[[2 3 4]
 [3 4 5]
 [4 5 6]]
